export const GET_ALL_PRODUCTS_REQUEST ='GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS ='GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAIL ='GET_ALL_PRODUCTS_FAIL';
export const SORT_AND_FILTER = 'SORT AND_FILTER'